### ISSUE TITLE
Marc serialization broken for demo records

### ISSUE THREAD

**Issue by aw-bib** [inveniosoftware/invenio-records#169]
E.g. record 115 (title:"Influence of processing parameters") does not properly serialize in Marc21.

```
[2017-03-23 15:57:13,577] ERROR in app: Exception on /record/115/export/marcxml [GET]
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/invenio_records_ui/views.py", line 207, in record_view
    return view_method(pid, record, template=template, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/invenio_records_ui/views.py", line 255, in export
    data = serializer.serialize(pid, record)
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/invenio_marc21/serializers/marcxml.py", line 82, in serialize
    return dumps(self.transform_record(pid, record, links_factory),
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/invenio_marc21/serializers/dojson.py", line 65, in transform_record
    links_factory=links_factory))
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/invenio_marc21/serializers/marcxml.py", line 70, in dump
    return super(MARCXMLSerializer, self).dump(obj)
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/invenio_marc21/serializers/dojson.py", line 53, in dump
    return GroupableOrderedDict(self.dojson_model.do(obj))
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/dojson/contrib/to_marc21/model.py", line 64, in do
    blob = GroupableOrderedDict(blob)
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/dojson/utils.py", line 217, in __new__
    value = GroupableOrderedDict(value)
  File "/home/vagrant/.virtualenvs/invenio/local/lib/python2.7/site-packages/dojson/utils.py", line 192, in __new__
    v = values[key]
KeyError: u'access_method'
127.0.0.1 - - [23/Mar/2017 15:57:13] "GET /record/115/export/marcxml HTTP/1.0" 500 -
```

(Noted at the IUGW2017)

**Comment by lnielsen** [comment]
Add selenium tests or just pytest to test all records serialisations

**Comment by jbenito3** [comment]
see invenio-app-ils#44 and invenio-records#180
