### ISSUE TITLE
`after_update` triggered by `get_record`

### ISSUE THREAD

**Issue by dset0x** [inveniosoftware/invenio-records#24]
When calling `get_record` from within celery, in parallel, it is possible to trigger a record update on ES, involuntarily:
```
[38]   /home/gs-sis/.virtualenvs/invenio/src/invenio-checker/invenio_checker/conftest2.py(384)_pytest_sessionstart()
-> r=get_record(i)
[39]   /home/gs-sis/.virtualenvs/invenio/src/invenio-records/invenio_records/api.py(125)get_record()
-> obj = RecordMetadata.query.get(recid)
[40]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py(819)get()
-> return self._get_impl(ident, loading.load_on_ident)
[41]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py(852)_get_impl()
-> return fallback_fn(self, key)
[42]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py(219)load_on_ident()
-> return q.one()
[43]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py(2473)one()
-> ret = list(self)
[44]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py(2515)__iter__()
-> self.session._autoflush()
[45]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py(1282)_autoflush()
-> self.flush()
[46]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py(2004)flush()
-> self._flush(objects)
[47]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py(2086)_flush()
-> flush_context.execute()
[48]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py(373)execute()
-> rec.execute(self)
[49]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py(532)execute()
-> uow
[50]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py(186)save_obj()
-> update_version_id in states_to_update
[51]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py(956)_finalize_insert_update_commands()
-> mapper.dispatch.after_update(mapper, connection, state)
[52]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/event/attr.py(256)__call__()
-> fn(*args, **kw)
[53]   /home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/events.py(550)wrap()
-> fn(*arg, **kw)
[54] > /home/gs-sis/.virtualenvs/invenio/src/invenio/invenio/ext/es.py(276)new_record()
-> index_record.delay(target.id)
```

This later manifests itself with an exception:
```
Traceback (most recent call last):
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/_pytest/main.py", line 82, in wrap_session
    config.hook.pytest_sessionstart(session=session)
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/home/gs-sis/.virtualenvs/invenio/src/invenio-checker/invenio_checker/conftest2.py", line 377, in pytest_sessionstart
    return _pytest_sessionstart(session)
  File "/home/gs-sis/.virtualenvs/invenio/src/invenio/invenio/base/helpers.py", line 52, in decorated_func
    result = f(*args, **kwargs)
  File "/home/gs-sis/.virtualenvs/invenio/src/invenio-checker/invenio_checker/conftest2.py", line 388, in _pytest_sessionstart
    r=get_record(i)
  File "/home/gs-sis/.virtualenvs/invenio/src/invenio-records/invenio_records/api.py", line 125, in get_record
    obj = RecordMetadata.query.get(recid)
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 819, in get
    return self._get_impl(ident, loading.load_on_ident)
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 852, in _get_impl
    return fallback_fn(self, key)
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident
    return q.one()
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2473, in one
    ret = list(self)
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2515, in __iter__
    self.session._autoflush()
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1282, in _autoflush
    self.flush()
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/home/gs-sis/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 712, in _emit_update_statements
    (table.description, len(records), rows))
StaleDataError: UPDATE statement on table 'record_json' expected to update 1 row(s); 0 were matched.
```

Could it be that I am using the session wrong? Shouldn't these calls go though `flask-sqlalchemy` instead, as they do from inside `inveniomanage shell`?

---

Mind you that when picking up the record again in another celery task, this actually commits to the database as well, without ever having called commit.

**Comment by dset0x** [comment]
This appears to solve the problem for me, but I don't know what the side-effects, or lack of thereof cause.

```diff
diff --git a/invenio_records/api.py b/invenio_records/api.py
index 2a441f4..8e251e5 100644
--- a/invenio_records/api.py
+++ b/invenio_records/api.py
@@ -122,7 +123,8 @@ class Record(SmartDict):
 
     @classmethod
     def get_record(cls, recid, *args, **kwargs):
-        obj = RecordMetadata.query.get(recid)
+        with db.session.no_autoflush:
+            obj = RecordMetadata.query.get(recid)
         return cls(obj.json, model=obj) if obj else None
 
     def dumps(self, **kwargs):
```

cc @jalavik

**Comment by jirikuncar** [comment]
@dset0x it might be caused by comiting `bibrec` table, hence `no_autoflush` seems like good temporary solution.
