### ISSUE TITLE
sqlalchemy_continuum dependency issue upgrading from 1.3.0 to 1.4.0

### ISSUE THREAD

**Issue by alisonrclarke** [inveniosoftware/invenio-records#250]
Package version (if known): 1.4.0

## Describe the bug
`sqlalchemy_continuum` is not installed as a dependency of `invenio_records` (or of `invenio_db`) but is required by [invenio_records.api](https://github.com/inveniosoftware/invenio-records/blob/d0a273ebbfb51bd7105c23f9b61f13cba8f40ff8/invenio_records/api.py#L20).

 
## Steps to Reproduce
1. Create an app using v1.3.0 of `Invenio-records` without installing `sqlalchemy_continuum` (e.g. the [HEPData app](https://github.com/HEPData/hepdata).
2. Upgrade the app to use `Invenio-records` v1.4.0 (and other associated invenio dependencies).
3. Run the app and get an error:

```bash
(hepdata) (base) DA-IARC-01:hepdata myuser$ hepdata run --debugger --reload
Traceback (most recent call last):
  File "/Users/myuser/.virtualenvs/hepdata/bin/hepdata", line 33, in <module>
    sys.exit(load_entry_point('hepdata', 'console_scripts', 'hepdata')())
  File "/Users/myuser/.virtualenvs/hepdata/bin/hepdata", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/myuser/.virtualenvs/hepdata/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 100, in load
    module = import_module(match.group('module'))
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/myuser/Documents/dev/HEPData/src/hepdata/hepdata/cli.py", line 31, in <module>
    from hepdata.ext.elasticsearch.admin_view.api import AdminIndexer
  File "/Users/myuser/Documents/dev/HEPData/src/hepdata/hepdata/ext/elasticsearch/admin_view/api.py", line 33, in <module>
    from hepdata.modules.records.utils.common import get_record_contents
  File "/Users/myuser/Documents/dev/HEPData/src/hepdata/hepdata/modules/records/utils/common.py", line 27, in <module>
    from invenio_records.api import Record
  File "/Users/myuser/.virtualenvs/hepdata/lib/python3.7/site-packages/invenio_records/__init__.py", line 331, in <module>
    from .api import Record
  File "/Users/myuser/.virtualenvs/hepdata/lib/python3.7/site-packages/invenio_records/api.py", line 19, in <module>
    from sqlalchemy_continuum.utils import parent_class
ModuleNotFoundError: No module named 'sqlalchemy_continuum'
```

## Expected behavior

The app should run without requiring `sqlalchemy_continuum`, as installing it [enables versioning support in `invenio-db`](https://invenio-db.readthedocs.io/en/latest/configuration.html?highlight=continuum#DB_VERSIONING) and thus changes the behaviour.

(Workaround is to install `sqlalchemy_continuum` and set `DB_VERSIONING = False` in the config.)

## Additional context

Running on MacOS 11.2.1, python 3.7.

**Comment by lnielsen** [comment]
Apologies for the long delay in replying. The ``versioning`` dependency was added in 7b4fe7ed944fe29db0ddca11620797f1a56ce185 (but will not be part of the v1.4 release but only later releases). Records won't work without the sqlalchemy_continuum, but you can create record classes without versioning support, but the transaction table will always be created.

Long-term, SQLAlchemy-Continuum is not updated very often causing upgrade issues, so we're likely to look for a local solution and remove the module at a later date.
