### ISSUE TITLE
api: creating record containing specific recid

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio-records#39]
*This problem has already being mused a bit IRL but not on GitHub.*

Currently if one tries to load records having specified recid `invenio-records` crashes with:
```python
-------------------------------------------------------------------------------
ERROR in api [.../invenio_records/api.py:94]:
Problem creating a record.
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File ".../invenio_records/api.py", line 88, in create
    db.session.commit()
  File ".../sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File ".../sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File ".../sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File ".../sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File ".../sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File ".../sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File ".../sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File ".../sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File ".../sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File ".../sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File ".../sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File ".../sqlalchemy/orm/persistence.py", line 748, in _emit_insert_statements
    execute(statement, multiparams)
  File ".../sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File ".../sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File ".../sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File ".../sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File ".../sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File ".../sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File ".../sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File ".../sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File ".../MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File ".../MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`inspire`.`record_json`, CONSTRAINT `record_json_ibfk_1` FOREIGN KEY (`id`) REFERENCES `bibrec` (`id`))') [SQL: u'INSERT INTO record_json (id, version_id, json) VALUES (%s, %s, %s)'] [...]
```

The implicit desired behavior would be that the record is well uploaded and the given recid is stored correctly in `pidstore`/`bibrec` tables.

**Comment by lnielsen** [comment]
This problem have been solved in 1.0.0aX. Records module now never touches the JSON being stored in anyway. It's the responsibility of the one creating the record to include any recid/control numbers etc into the JSON (some PIDStore minters do this for you).

Each record is now identified by a UUID (not stored in the JSON). This UUID can either be generated by the one creating the record or automatically generated by the underlying model:

```python
# Set by you
Records.create({'title': 'My title'}, id_=uuid.uuid4())
# Automatically set by records:
Records.create({'title': 'My title'})
```

If a UUID provided by the user already exists, the record creation will fail with an IntegrityError.
